ccad/config/routes.rb
Ccad::Application.routes.draw do

  get "password_resets/new"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users do
    get "admin" => "admin#show"
    get "admin_index" => "admin#index"
    
  end
  
  resources :users do
    resources :contacts
  end
  
  resources :users do
    resources :jr_researches
  end

  
  resources :users do
    resources :interest_users  
  end
  
  resources :users do 
    resources :interests
  end
  
  resources :password_resets
  

end

ccad/app/models/interest_user.rb
"""
0|id|INTEGER|1||1
1|user_id|integer|0||0
2|interest_id|integer|0||0
3|created_at|datetime|1||0
4|updated_at|datetime|1||0
"""

class InterestUser < ActiveRecord::Base
  attr_accessible :id, :user_id, :interest_id
  
  belongs_to :user
  
  has_many :interests
  has_many :users
  
  def update_all(interests, contact)
    
    interest_users = InterestUser.find(:all, :conditions => { :user_id=>contact.user_id })
    logger.info("#{interest_users}")
    
    interest_users.each do |i|
      i.destroy
    end
    
    # For the first entry, update the interest_id from blank to the first.
    interests.each do |i|
      InterestUser.find_or_create_by_user_id_and_interest_id(:user_id=>contact.user_id, :interest_id=>i)
    end  
  end
end

ccad/app/controllers/interest_users_controller.rb
class InterestUsersController < ApplicationController
  # GET /interest_users
  # GET /interest_users.json
  
  skip_before_filter :authorize, :only => [:new, :create] 
  before_filter :authorize_super, :only => [:new, :create]
  before_filter :user_filter
  
  
  def index
    @interest_users = InterestUser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interest_users }
    end
  end

  # GET /interest_users/1
  # GET /interest_users/1.json
  def show
    @interest_user = InterestUser.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interest_user }
    end
  end

  # GET /interest_users/new
  # GET /interest_users/new.json
  def new
    @interest_user = InterestUser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interest_user }
    end
  end

  # GET /interest_users/1/edit
  def edit
    @interest_user = InterestUser.find(params[:id])
    @contact = Contact.find_by_user_id(session[:user_id])
    @selected = InterestUser.find(:all, :conditions => { :user_id => params[:user_id] })
  end

  # POST /interest_users
  # POST /interest_users.json
  def create
    @interest_user = InterestUser.new(params[:interest_user])

    respond_to do |format|
      if @interest_user.save
        format.html { redirect_to @interest_user, notice: 'User interest was successfully created.' }
        format.json { render json: @interest_user, status: :created, location: @interest_user }
      else
        format.html { render action: "new" }
        format.json { render json: @interest_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interest_users/1
  # PUT /interest_users/1.json
  def update
    @all_interest_users = params[:inters]
    logger.info(" interest -- #{@all_interest_users}")
    @interest_users = @all_interest_users[:interest_id]
    logger.info("interest IDs -- #{@interest_users}")
    @interest_user = InterestUser.find(params[:id])
    
    @contact = Contact.find_by_user_id(session[:user_id])
    
    respond_to do |format|

      @interest_user.update_all(@interest_users, @contact)
      if @interest_user.update_attributes(params[:interest_user])
        format.html { redirect_to user_admin_url(@user), notice: 'Your profile has been successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interest_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interest_users/1
  # DELETE /interest_users/1.json
  def destroy
    @interest_user = InterestUser.find(params[:id])
    @interest_user.destroy

    respond_to do |format|
      format.html { redirect_to interest_users_url }
      format.json { head :no_content }
    end
  end
  
  protected
  def user_filter
    @user = User.find(session[:user_id])
  end
end

ccad/app/views/interest_users/_fields.html.erb
<p>
  Select your Interests from the list below:</p>
  
<div id="interests">
  <%= render :partial => 'interest', :collection => Interest.all %>
</div>
<p><%= add_interest_link("Add Another Interest") %></p>

ccad/app/views/interest_users/_form.html.erb
<%= form_for ([@user, @interest_user]), :html => {:class=>"form-horizontal form-main", :style=>"margin-left: 100px;"}, :url => {:controller => 'interest_users', :action => 'update', :id => params[:id]} do |f| %>


  <fieldset>
    <p style="margin-left: 40px;">Select your research interests:</p>
    
    <div class="field">
      <select name="inters[interest_id][]" multiple="true" size="20">
        <% logger.info("#{@selected}")%>
        <%= options_from_collection_for_select(Interest.all, 'id', 'area', :selected => @selected.collect {|s| s.interest_id} ) %>
      </select>
    </div>


  <div class="actions">
    <%= f.submit "Complete", :class=>"btn-main", :style => "margin-left: 80px;" %>
  </div>

  </fieldset>
  
<% end %>

ccad/app/views/interest_users/_interest.html.erb
<div class="interest">
  <% fields_for_interest(@user_interest) do |user_interest_form| %>
  <p>
    <% hidden_field_tag :user_id, @user_interest.user_id %>
    Interest: <%= user_interest_form.collection_select :interest_id, Interest.all, :id, :area %>
    <%= link_to_function "remove", "$(this).up('.task').remove()" %>
  </p>
  <% end %>
</div>

ccad/app/views/interest_users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span4">
        <%= render "side_nav" %>
      </div>
      <div class="span6">
        <h2 style="margin-bottom: 40px;" class="dots_back">What are your areas of interest?</h2>

        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

ccad/app/views/interest_users/editold.html.erb
<h1>Editing user_interest</h1>

<% form_for :user_interest, :url => user_interest_path(@user_interest), :html => { :method => 'put' } do |f| %>
  <%= render :partial => 'fields', :locals => { :f => f } %>
  <p><%= submit_tag "Confirm" %>
<% end %>

<%= link_to 'Show', @user_interest %> |
<%= link_to 'Back', user_interests_path %>

ccad/app/views/interest_users/index.html.erb
<h1>Users and Interests</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Interest</th>
    <th></th>
  </tr>

<% @interest_users.each do |interest_user| %>
  <tr>
    <td><%= User.find(interest_user.user_id).name %></td>
    <% if interest_user.interest_id.nil? %>
      <td>N/A</td>
    <% else %>
      <td><%= Interest.find(interest_user.interest_id).area %></td>
    <% end %>
    <td><%= link_to 'Show', interest_user %></td>
    <td><%= link_to 'Edit', edit_interest_user_path(interest_user) %></td>
    <td><%= link_to 'Destroy', interest_user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User interest', new_interest_user_path %>

ccad/app/views/interest_users/new.html.erb
<h1>New interest_user</h1>

<% form_for :interest_user, :url => interest_users_path do |f| %>
  <%= render :partial = 'fields', :locals => { :f => f } %>
  <p><%= submit_tag "Confirm" %></p>

<%= link_to 'Back', interest_users_path %>