ccad copy/config/routes.rb
Ccad::Application.routes.draw do

  get "password_resets/new"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users do
    get "admin" => "admin#show"
    get "admin_index" => "admin#index"
    
  end
  
  resources :users do
    resources :contacts
  end
  
  resources :users do
    resources :jr_researches
  end

  
  resources :users do
    resources :interest_users  
  end
  
  resources :users do 
    resources :interests
  end
  
  resources :password_resets
  

end

ccad copy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
  protected
  
    def authorize
      logger.info("ID #{session[:user_id]}")
      if session[:user_id] == nil
        redirect_to login_url, :notice => "Please log in."
      else
        unless User.find_by_id(session[:user_id])
          redirect_to login_url, :notice => "Please log in."
        end
    
    
        if User.find(session[:user_id]) != User.find(params[:user_id])
          redirect_to login_url, :notice => "Please log in."
        end
      end
    end
    
    
    def authorize_super
      if session[:user_id] == nil
        redirect_to login_url, :notice => "Please log in."
      end
      user = User.find_by_id(session[:user_id])
      unless session[:user_id] == 1
        logger.info("#{session[:user_id]} id not 1")
        redirect_to login_url, :notice => "Please log in."
        logger.info("redirecting")
      end
    end
    
  private
  def current_user
    @current_user ||= User.find_by_auth_token( cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user
end

ccad copy/app/helpers/application_helper.rb
module ApplicationHelper
end

ccad copy/app/views/application/_nav.html.erb
<%-# Navbar, general for now. %>
<div class="container" style="width: 100%">
  <div class="container fixed_nav top_white">
    <ul class="nav nav-tabs tan fixed_nav" style="float: left; min-width: 1100px;">
      <li><a href="http://ccad.local/index.php"><%= image_tag("2014logo.png", :class=>"logo_top") %></a></li>
    </ul>
  </div>
</div>

<div class="red_bar"></div>

ccad copy/app/views/application/_nav_super.html.erb
<%-# Navbar, general for now. %>
<div class="container" style="width: 100%">
  <div class="container fixed_nav top_white">
    <ul class="nav nav-tabs tan fixed_nav" style="float: left; min-width: 1100px;">
      <li><a href="http://ccad.local/index.php"><%= image_tag("2014logo.png", :class=>"logo_top") %></a></li>
      
      <% @user = params[:user_id] %>
      <% logger.info("#{@user_id}")%>
        <li style="margin-left: 20%"><%= link_to "Logout", logout_path, :method => :delete, :redirect_to => login_path %></h7>
    </ul>
  </div>
</div>

<div class="red_bar"></div>

ccad copy/app/views/application/_nav_user.html.erb
<%-# Navbar, general for now. %>
<div class="container" style="width: 100%">
  <div class="container fixed_nav top_white">
    <ul class="nav nav-tabs tan fixed_nav" style="float: left; min-width: 1100px;">
      <li><a href="http://ccad.local/index.php"><%= image_tag("2014logo.png", :class=>"logo_top") %></a></li>
   
		  <li style="margin-left: 20%"><%= link_to "Logout", logout_path, :method => :delete, :redirect_to => login_path %></h7>
    </ul>
  </div>
</div>

<div class="red_bar"></div>

ccad copy/app/views/application/_side_nav.html.erb
<div class="nav-sidebar">
  <p class="nav-side"><%= link_to "Your Profile", user_admin_path(@user) %></p>
  <p class="nav-side"><%= link_to "Update Your Profile", edit_user_contact_path(@user, @contact) %></p>
  <p class="nav-side"><%= link_to "View Other Profiles", user_contacts_path(@user) %></p>
  <p class="nav-side"><%= link_to "Research Interests", user_interests_path(@user) %></p>
</div>

ccad copy/app/views/application/_side_nav_super.html.erb
<div class="nav-sidebar">
  <p class="nav-side"><%= link_to "All Users", users_path %></p>
  <p class="nav-side"><%= link_to "Add a New User", new_user_path %></p>
  <p class="nav-side"><%= link_to "Edit Interests", user_interests_path(@user) %></p>
  
</div>