ccad/config/routes.rb
Ccad::Application.routes.draw do

  get "password_resets/new"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users do
    get "admin" => "admin#show"
    get "admin_index" => "admin#index"
    
  end
  
  resources :users do
    resources :contacts
  end
  
  resources :users do
    resources :jr_researches
  end

  
  resources :users do
    resources :interest_users  
  end
  
  resources :users do 
    resources :interests
  end
  
  resources :password_resets
  

end

ccad/app/models/contact.rb
"""
0|id|INTEGER|1||1
1|user_id|integer|0||0
2|firstname|varchar(255)|0||0
3|lastname|varchar(255)|0||0
4|email|varchar(255)|0||0
5|address_street1|varchar(255)|0||0
6|address_street2|varchar(255)|0||0
7|address_city|varchar(255)|0||0
8|address_state|varchar(255)|0||0
9|address_zip|varchar(255)|0||0
10|picture_url|varchar(255)|0||0
11|created_at|datetime|1||0
12|updated_at|datetime|1||0
13|phone|string|0||0
"""

class Contact < ActiveRecord::Base
  attr_accessible :id, :user_id, :avatar, :firstname, :lastname, :email, :address_street1, :address_street2, :address_city, :address_state, :address_zip, :picture_url, :phone, :title, :phd_md

  belongs_to :user
  
  mount_uploader :avatar, AvatarUploader

   def remove_avatar!
     begin
       super
     rescue Fog::Storage::Rackspace::NotFound
     end
   end

   def remove_previously_stored_avatar
     begin
       super
     rescue Fog::Storage::Rackspace::NotFound
       @previous_model_for_avatar = nil
     end
   end
  
  
end

ccad/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  
  before_filter :authorize, :except => [:new, :create] 
  before_filter :authorize_super, :only => [:new, :create]
  before_filter :user_filter
  
  def index
    @contacts = Contact.all
    @contact = Contact.find_by_user_id(session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])
    @jr_research = JrResearch.find_by_user_id(@contact.user_id)
    @user_contact = Contact.find_by_user_id(params[:user_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
    if @contact.user_id != session[:user_id]
      redirect_to login_url, :notice => "Please log in."
    end
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])
    @jr_research = JrResearch.find_by_user_id(@user.id)
    
    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to edit_user_jr_research_url(@user, @jr_research) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
  
  protected 
  def user_filter
    @user = User.find(session[:user_id])
  end
  

end

ccad/app/helpers/contacts_helper.rb
module ContactsHelper
  
  def us_states
    [ 
      ['', ''],
      ['AK', 'AK'],
      ['AL', 'AL'],
      ['AR', 'AR'],
      ['AZ', 'AZ'],
      ['CA', 'CA'],
      ['CO', 'CO'],
      ['CT', 'CT'],
      ['DC', 'DC'],
      ['DE', 'DE'],
      ['FL', 'FL'],
      ['GA', 'GA'],
      ['HI', 'HI'],
      ['IA', 'IA'],
      ['ID', 'ID'],
      ['IL', 'IL'],
      ['IN', 'IN'],
      ['KS', 'KS'],
      ['KY', 'KY'],
      ['LA', 'LA'],
      ['MA', 'MA'],
      ['MD', 'MD'],
      ['ME', 'ME'],
      ['MI', 'MI'],
      ['MN', 'MN'],
      ['MO', 'MO'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['NC', 'NC'],
      ['ND', 'ND'],
      ['NE', 'NE'],
      ['NH', 'NH'],
      ['NJ', 'NJ'],
      ['NM', 'NM'],
      ['NV', 'NV'],
      ['NY', 'NY'],
      ['OH', 'OH'],
      ['OK', 'OK'],
      ['OR', 'OR'],
      ['PA', 'PA'],
      ['RI', 'RI'],
      ['SC', 'SC'],
      ['SD', 'SD'],
      ['TN', 'TN'],
      ['TX', 'TX'],
      ['UT', 'UT'],
      ['VA', 'VA'],
      ['VT', 'VT'],
      ['WA', 'WA'],
      ['WI', 'WI'],
      ['WV', 'WV'],
      ['WY', 'WY']
    ]
  end
  
end

ccad/app/views/contacts/_form.html.erb
<%= form_for ([@user, @contact]), :html => {:class=>"form-horizontal form-main"} do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <% @contact.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  
  <control-groupset>

    <div class="control-group">
      <%= f.label :title, "Title", :class => "control-label" %>
      <%= f.text_field :title, :class => "controls" %>
    </div>
    
    <div class="control-group">
      <%= f.label :firstname, "First Name", :class=>"control-label" %>
      <%= f.text_field :firstname, :class => "controls" %>
    </div>
    
    <div class="control-group">
      <%= f.label :lastname, "Last Name", :class=>"control-label"%>
      <%= f.text_field :lastname, :class => "controls" %>
    </div>
    
    <div class="control-group">
      <%= f.label :phd_md, "Suffix", :class=>"control-label", :style=>"padding-right: 20px;" %>
      <div class="controls">
        <%= f.select :phd_md, {"PhD" => "PhD", "MD" => "MD"} %>
      </div>
    <div>
      
    <div class="control-group">
      <%= f.label :email, "Email Address", :class=>"control-label" %>
      <%= f.text_field :email, :class => "controls" %>
    </div>
      
    <div class="control-group">
      <%= f.label :phone, "Phone Number", :class=>"control-label" %>
      <%= f.text_field :phone, :class => "controls" %>
    </div>
    
    <div class="control-group">
      <%= f.label :address_street1, "Street Address 1", :class=>"control-label" %>
      <%= f.text_field :address_street1, :class => "controls" %>
    </div>  
    
    <div class="control-group">
      <%= f.label :address_street2, "Street Address 2", :class=>"control-label" %>
      <%= f.text_field :address_street2, :class => "controls" %>
    </div>  
    
    <div class="control-group">
      <%= f.label :address_city, "City", :class=>"control-label" %>
      <%= f.text_field :address_city, :class => "controls" %>
    </div>  
    
    <div class="control-group">
      <%= f.label :address_state, "State", :class=>"control-label", :style=>"padding-right: 20px;" %>
      <div class="controls">
        <%= f.select :address_state, us_states %>
      </div>
    </div>  
    
    <div class="control-group">
      <%= f.label :address_zip, "Zip Code", :class=>"control-label" %>
      <%= f.text_field :address_zip, :class => "controls" %>
    </div>
    
    <div class="control-group">
      <p style="width:300px; font-size:12px;">Upload a profile picture (images will be resized to a 100px x 100px thumbnail).  Only .jpg, .jpeg, .png or .gif files will be accepted.</p>
  		<%= image_tag(@contact.picture_url) if @contact.avatar? %>
  		<%= f.file_field :avatar %>
    </div>
    
    
  <div class="actions">
    <%= f.submit "Next", :class=>"btn-main", :style => "margin-left: 180px;" %>
  </div>
  </control-groupset>
<% end %>

ccad/app/views/contacts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span4">
        <%= render "side_nav" %>
      </div>
      <div class="span6">
        <h2 class="dots_back">Update Your Contact Information</h2>
        <br /><br />
        <%= render 'form' %>
      </div>

    </div>
  </div>
</div>
</div>
</div>

ccad/app/views/contacts/index.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span3">
        <%= render "side_nav" %>
      </div>
      <div class="span8">
        <h1 style="margin-top: 50px;">Other Researchers</h1>
  
        <ul class="thumbnails" style="margin-left: 50px;">

          <% @contacts.each do |contact| %>

            <% @user = User.find(contact.user_id) %>
            <% jr_research = JrResearch.find_by_user_id(contact.user_id) %>
            <% @current_user = User.find(params[:user_id]) %>
          
            <% if @user.id == 1 %>
            <% else %>
                <li class="thumbnail span2">
                  <% if contact.avatar? %>
                    <%= link_to image_tag(contact.avatar_url(:thumb).to_s, :class=>"pic"), user_contact_path(@current_user, contact) %>
                  <% else %>
                    <%= link_to image_tag("no_pic.png", :class=>"pic"), user_contact_path(@current_user, contact) %>        </li>
                  <% end %>
                  <div class="caption">
                  <h4 class="center"><%= contact.title %> <%= contact.firstname %> <%= contact.lastname %></h4>
                  <p class="small_text"><%= jr_research.current_uni %></p>
                  <p class="small_text"><%= jr_research.uni_department %></p>
                </div>
              </li>
          
            <% end %>
          <% end %>
          </ul>
          <br />
      </div>
    </div>
  </div>
</div>

ccad/app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

ccad/app/views/contacts/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span3">
        <%= render "side_nav" %>
      </div>
      <div class="span8">
        <div style="margin-top: 40px;">
          <h2><%= @contact.firstname %> <%= @contact.lastname %></h2>
        </div>
        <div class="main_div">
        <% if @contact.firstname.nil? %>
          <p class="center">Your profile is currently empty.  Please <%= link_to "update", edit_user_contact_url(@user, @contact) %> your details.</p>
        <% else %>
          <div class="span2">
            <% if @contact.avatar? %>
              <%= image_tag(@contact.avatar_url(:thumb).to_s, :class=>"prof_pic") %>
            <% else %>
              <%= image_tag("no_pic.png", :class => "prof_pic") %>
            <% end %>
          </div>
          <div class="span5">
            
          <h4><%= @jr_research.current_uni %><br /></h4>
          <h5><%= @jr_research.uni_department %></h5>
  
  
          <% if @contact.address_street1? %>
            <h4><br /><%= @contact.address_street1 %>
            <%= @contact.address_street2 %><br /><%= @contact.address_city %>, <%= @contact.address_state %> <%= @contact.address_zip %></h4>
          <% end %>
          <% if @contact.email %>
            <h4><%= mail_to @contact.email %></h4>
          <% else %>
            <h4><%= mail_to @user.name %></h4>
          <% end %>
        <% end %>
        
        <% @interest_users = InterestUser.find(:all, :conditions => {:user_id=>@contact.user_id}) %>
        <h4>Research Interests</h4>
          <% @interest_users.each do |interest_user| %>
            <% interest_id = interest_user.interest_id %>
            <% if interest_id.nil? %>
              <p style="line-height: 11px;">None Listed</p>
            <% else %>
              <% @interest = Interest.find(interest_id).area %>
              <p style="line-height: 11px;"><%= link_to @interest.area, interest_path(@interest) %></p>
            <% end %>
          <% end %>
          
          <% if @jr_research.attachment_url.nil? %>
          <% else %>
            <h4><%= link_to "Download Resume", @jr_research.attachment_url, :target => "_blank" %></h4>
          <% end %>
          
        </div>
        
        </div>
        </div>
      </div>
    </div>
  </div>
</div>