ccad copy/config/routes.rb
Ccad::Application.routes.draw do

  get "password_resets/new"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users do
    get "admin" => "admin#show"
    get "admin_index" => "admin#index"
    
  end
  
  resources :users do
    resources :contacts
  end
  
  resources :users do
    resources :jr_researches
  end

  
  resources :users do
    resources :interest_users  
  end
  
  resources :users do 
    resources :interests
  end
  
  resources :password_resets
  

end

ccad copy/app/models/interest.rb
"""
0|id|INTEGER|1||1
1|area|varchar(255)|0||0
2|created_at|datetime|1||0
3|updated_at|datetime|1||0
"""

class Interest < ActiveRecord::Base
  attr_accessible :id, :area

  has_many :users, :through => :interest_users
  belongs_to :interest_user
  
end

ccad copy/app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  # GET /interests
  # GET /interests.json
  
  
  before_filter :authorize, :only => [:index, :show]
  before_filter :authorize_super, :except => [:index, :show]
  before_filter :user_filter
  
  
  def index
    @interests = Interest.all
    @user = session[:user_id]
    @contact = Contact.find_by_user_id(session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interests }
    end
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
    @interest = Interest.find(params[:id])
    @interest_users = InterestUser.find(:all, :conditions => {:interest_id=>@interest.id})
    logger.info("#{@interest_users}")
    @contact = Contact.find_by_user_id(session[:user_id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interest }
    end
  end

  # GET /interests/new
  # GET /interests/new.json
  def new
    @interest = Interest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interest }
    end
  end

  # GET /interests/1/edit
  def edit
    @interest = Interest.find(params[:id])
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(params[:interest])

    respond_to do |format|
      if @interest.save
        format.html { redirect_to user_interests_url(@user), notice: 'Interest was successfully created.' }
        format.json { render json: user_interests_url(@user), status: :created, location: @interest }
      else
        format.html { render action: "new" }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interests/1
  # PUT /interests/1.json
  def update
    @interest = Interest.find(params[:id])

    respond_to do |format|
      if @interest.update_attributes(params[:interest])
        format.html { redirect_to user_interests_url(@user), notice: 'Interest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest = Interest.find(params[:id])
    @interest.destroy

    respond_to do |format|
      format.html { redirect_to user_interests_url(@user) }
      format.json { head :no_content }
    end
  end
  
  protected
  def user_filter
    @user = User.find(session[:user_id])
  end
end

ccad copy/app/helpers/interests_helper.rb
module InterestsHelper
end

ccad copy/app/views/interests/_form.html.erb
<%= form_for ([@user, @interest]), :html=>{:class=>"form-horizontal form-main"} do |f| %>
  <% if @interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% @interest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
    
    <div class="controls">
      <%= f.label :area, "Research Area", :class=>"control-label" %>
      <%= f.text_field :area, :class=>"controls" %>
    </div>
    
  <div class="actions">
    <%= f.submit "Update", :class=>"btn-main", :style => "margin-left: 180px;" %>
  </div>
<% end %>

ccad copy/app/views/interests/_interests.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span4">
        <div class="nav-sidebar">
          <p class="nav-side"><%= link_to "Your Profile", user_admin_path(@user) %></p>
          <p class="nav-side"><%= link_to "Update Your Profile", edit_user_contact_path(@user, @contact) %></p>
          <p class="nav-side"><%= link_to "View Other Profiles", user_contacts_path(@user) %></p>
          <p class="nav-side"><%= link_to "Research Interests", user_interests_path(@user) %></p>
        </div>
      </div>
      
      <div class="span6">
        <h2 style="margin-bottom: 40px;" class="dots_back">All Interests</h2>
        
        <div class="interest_main">
          <% @interests.each do |interest| %>
            <p><%= link_to interest.area, user_interest_path(@user, interest) %></p>
          <% end %>
        </div>
        
      </div>
    </div>
  </div>
</div>

ccad copy/app/views/interests/_interests_super.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span4">
        <%= render "side_nav_super" %>
      </div>
      
      <div class="span6">
        <h2>All Interests</h2>
        
        <h5 style="text-align: center;"><%= link_to "Add a New Interest", new_user_interest_path(@user) %></h5>
        
        <table class="table table-hover">
          <tr>
            <th>Interest</th>
            <th></th>
          </tr>
        
          <% @interests.each do |interest| %>
            <tr>
              <td><%= interest.area %></td>
              <td><%= link_to "Edit", edit_user_interest_path(@user, interest) %> | <%= link_to "Delete", user_interest_path(@user, interest), confirm: 'Are you sure?', method: :delete %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

ccad copy/app/views/interests/edit.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span4">
        <%= render "side_nav_super" %>
      </div> 
      <div class="span6">
      
        <h2 style="margin-bottom: 40px; margin-top: 40px;">Edit <%= @interest.area %></h2>

        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

ccad copy/app/views/interests/index.html.erb
<% if params[:user_id] == "1" %>
  <% logger.info("#{session[:user_id]}")%>
  <%= render "interests_super" %>
<% else %>
  <%= render "interests" %>
<% end %>

ccad copy/app/views/interests/new.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span4">
        <%= render "side_nav_super" %>
      </div>
      <div class="span6">
        <h2>Add a New interest</h2>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

ccad copy/app/views/interests/show.html.erb
<div class="container">
  <div class="row">
    <div class="span12">
      <div class="span4">
        <div class="nav-sidebar">
          <p class="nav-side"><%= link_to "Your Profile", user_admin_path(@user) %></p>
          <p class="nav-side"><%= link_to "Update Your Profile", edit_user_contact_path(@user, @contact) %></p>
          <p class="nav-side"><%= link_to "View Other Profiles", user_contacts_path(@user) %></p>
          <p class="nav-side"><%= link_to "Research Interests", user_interests_path(@user) %></p>
        </div>
      </div>
      
      <div class="span6">
        <h2 style="margin-bottom: 40px;" class="dots_back"><%= @interest.area %></h2>
        
        <table class = "table ji_table">
        <% if @interest_users.empty? %>
          <h4 class="center">There is no one else who shares this interest right now.</h4>
        <% else %>
          <h4 class="center">Others interested:</h4>
        
          <% @interest_users.each do |interest_user| %>
            <% logger.info("USER ID=#{interest_user.user_id} PARAMS=#{params[:user_id]}")%>
            <% if interest_user.user_id.to_i != params[:user_id].to_i %>
          
              <tr>
              <% @contact = Contact.find_by_user_id(interest_user.user_id) %>
                <td>
                  <% if @contact.avatar? %>
                    <%= image_tag(@contact.avatar_url(:thumb).to_s, :class=>"small_pic") %>
                  <% else %>
                    <%= image_tag("no_pic.png", :class => "small_pic") %>
                  <% end %>
                </td>
                <td><%= @contact.firstname %> <%= @contact.lastname %></td>
              
                <td>  
                  <% @interest_users = InterestUser.find(:all, :conditions => {:user_id=>@contact.user_id}) %>
                    <% @interest_users.each do |interest_user| %>
                      <% interest_id = interest_user.interest_id %>
                      <% @interest = Interest.find(interest_id) %>
                      <p style="line-height: 11px;"><%= link_to @interest.area, user_interest_path(@user, @interest) %></p>
                    <% end %>
                </td>
                <td>
                  <%= mail_to @contact.email, "contact" %>
                </td>
              </tr>
        
            <% else %>
              <h4 class="center">There is no one else who shares this interest right now.</h4>
            <% end %>
          <% end %>
        <% end %>
      </table>
    
      <div class="divider"></div>
      
      <div class="interests_all">
        <p>Other Interests</p>
        <% Interest.all.each do |interest| %>
          <p><%= link_to interest.area, user_interest_path(@user, interest) %></p>
        <% end %>
      </div>
     
      <br />
    
     </div>
  </div>
  </div>
</div>